# Generated by Django 5.1.3 on 2024-11-15 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Christians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(60)])),
                ('religion', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
    ]
