# Generated by Django 5.1.3 on 2024-11-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christians', '0002_category_christian_delete_christians'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='christian',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='christian',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='christians.category'),
        ),
    ]
