# Generated by Django 5.1.3 on 2024-11-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christians', '0003_alter_christian_options_alter_christian_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='christian',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='christian',
            options={},
        ),
        migrations.RemoveField(
            model_name='christian',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='christian',
            name='date',
        ),
        migrations.RemoveField(
            model_name='christian',
            name='description',
        ),
        migrations.AddField(
            model_name='christian',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='christian',
            name='gender',
            field=models.CharField(default='Custom', max_length=6),
        ),
        migrations.AddField(
            model_name='christian',
            name='role',
            field=models.CharField(default='Christian', max_length=100),
        ),
        migrations.AddField(
            model_name='christian',
            name='status',
            field=models.CharField(default='Single', max_length=100),
        ),
        migrations.AddField(
            model_name='christian',
            name='username',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
