# Generated by Django 5.1.3 on 2024-11-21 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christians', '0004_remove_christian_category_alter_christian_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='christian',
            old_name='username',
            new_name='name',
        ),
    ]
