# Generated by Django 5.1.3 on 2024-11-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christians', '0005_rename_username_christian_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='christian',
            name='churchName',
            field=models.CharField(default='Zion Temple'),
        ),
    ]
