# Generated by Django 5.1.3 on 2024-11-22 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christians', '0006_christian_churchname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='christian',
            name='churchName',
        ),
    ]
