# Generated by Django 5.1.3 on 2024-11-22 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christians', '0007_remove_christian_churchname'),
        ('events', '0002_remove_event_location_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='christian',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='christians', to='events.event'),
        ),
    ]
