# Generated by Django 5.1.3 on 2024-11-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christians', '0008_christian_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='christian',
            name='event',
        ),
    ]
